Repository emuflight/EmuConfigurator, pull requests merged in 2020-12, with the labels that each got.

#294 CRSF Widget fixes
  locales/en/messages.json
  src/js/tabs/osd.js
Labels: in-testing, merge-able if approved

#293 auto-sort presets descending
  src/js/tabs/pid_tuning.js
Labels: in-testing, merge-able if approved

#292 0.3.2 presets dBoost iRelaxV2 capable
  src/js/tabs/pid_tuning.js
Labels: in-testing, merge-able if approved

#286 sharpness verbiage
  locales/en/messages.json
Labels: in-testing, merge-able if approved

#287 increase CLI timeouts and add debug logging
  src/js/CliAutoComplete.js
  src/js/tabs/cli.js
Labels: in-testing, merge-able if approved

#302 github actions workflow
  .github/workflows/build.yml
Labels: merge-able if approved

#304 NFE on switch mod
  src/js/tabs/pid_tuning.js
Labels: merge-able if approved, want-in-next-release

#301 Add IRC Ghost serial protocol option
  src/js/tabs/configuration.js
Labels: want-in-next-release
